### PR TITLE
Fix up-cpp and add up-rust protection rules

### PR DESCRIPTION
**Pull request by stevenhartley**

### CODE REVIEW

**Comment by netomi** [comment]
I fixed the status checks by verifying it via the web ui.

For up-cpp I misses that you have a second job "ci" in the workflow, so the original name was correct.
For up-rust, I used the names of the jobs rather their id as names have precedence.

**Review by netomi — APPROVED** [review]

**Comment by stevenhartley** [comment]
@netomi it doesn't seem to be working still, it is waiting for ci output but not able to get it: https://github.com/eclipse-uprotocol/up-cpp/pull/57

**Comment by stevenhartley** [comment]
@netomi is the issue the name "ci" vs "CI"?

**Comment by netomi** [comment]
omg, its late, and I missed that the job has a name:

```
ci:
    name: CI status checks
```

will fix it.

**Comment by netomi** [comment]
when a job has been given a name, you have to use that, blame GitHub not me :-D

**Comment by netomi** [comment]
btw. there is now a more dynamic dashboard at https://otterdog.eclipse.org/index where you can see your current configuration.

**Comment by stevenhartley** [comment]
@netomi interesting that 2fa is not turned on. I'll have to dig through my emails to check why not.

**Pull request merged**
