### PR TITLE
Add branch protection rules for up-client-android-java

### PR DESCRIPTION
**Pull request by stevenhartley**
Hope that the github workflow is connected correctly

### CODE REVIEW

**Comment by netomi** [comment]
The correct status check should be "build" which I also verified via the Web UI.

I tried to compile the rule to determine the check name from a workflow here: https://otterdog.readthedocs.io/en/latest/reference/organization/repository/status-check/

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live.

**Comment by stevenhartley** [comment]
Thank you @netomi

**Comment by netomi** [comment]
np, btw. we plan to roll out a bigger update to the self-service which is already active for 1 project (see https://github.com/eclipse-csi/.eclipsefdn/pull/6). If you interested we could enable it for your project quite soon as well.

**Comment by stevenhartley** [comment]
> np, btw. we plan to roll out a bigger update to the self-service which is already active for 1 project (see [eclipse-csi/.eclipsefdn#6](https://github.com/eclipse-csi/.eclipsefdn/pull/6)). If you are interested we could enable it for your project quite soon as well.

Do you have more info on what this is (the update) and how it affects us? Thanks

**Comment by netomi** [comment]
so till now, the self-service is working via a workflow that runs when a PR is created and a cli tool that somebody has to run once the PR is merged. The change bundles everything together in a GitHub App that reacts automatically on PRs and applies the changes automatically (at least most of them).

We also have various things in mind that we are going to add

- auto merging of PRs if certain conditions meet (e.g. approval from a project lead)
- improved dashboard  to highlight potential improvements to your config wrt security
- automated checks for things like security.md

**Pull request merged**
