### PR TITLE
Enabling 2-factor and adding springboot project

### PR DESCRIPTION
**Pull request by stevenhartley**

### CODE REVIEW

**Comment by netomi** [comment]
the two_factor_enforced setting can not be changed via otterdog, it can only be done manually via the Web UI as it will remove any member that has 2FA not enabled yet.

In your case, there are still 2 members that have not yet enabled it:

- adienzel
- frankghe

**Comment by stevenhartley** [comment]
> the two_factor_requirement setting can not be changed via otterdog, it can only be done manually via the Web UI as it will remove any member that has 2FA not enabled yet.
> 
> In your case, there are still 2 members that have not yet enabled it:
> 
> * adienzel
> * frankghe

What does "remove" mean? They are not active committers anymore, Frank is already retired and Adi will also be retired shortly.

**Comment by netomi** [comment]
"removed" means that GitHub will remove them from the GitHub organization. If they are not active committers anymore, I would suggest to start the process to retire them. frankghe is a contributor afaict, so you could remove him from the PMI, and he will be removed automatically by our sync script.

**Comment by stevenhartley** [comment]
That is fine. If they want to contribute in the future, they will need to turn 2-factor on. Please go ahead and enable it. Should I change this PR?

**Comment by netomi** [comment]
No you can leave it like that, I will make the necessary change afterwards.

**Review by netomi — APPROVED** [review]

**Comment by stevenhartley** [comment]
Thank you @netomi !

**Comment by netomi** [comment]
ftr: the annoying bug with the wrong cc lines is fixed

**Pull request merged**
