### PR TITLE
Allow merge commits on all Rust repos

### PR DESCRIPTION
**Pull request by PLeVasseur**
We are encouraging developers to submit PRs with clean, well structured commit histories. In order to preserve these commit histories *and* retain traceability to the original review, we are using merge commits.

### CODE REVIEW

**Review by gregmedd — APPROVED** [review]
LGTM

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
I would like to note one major disadvantage of using merge commit that I encoutered just recently.

If somebody creates a PR and does a lot of commits in this PR, all of them end up in the target branch as individual commits. They also count for any statistic calculation as individual commits and might give a wrong impression of the work that is actually happening on a project.

While every project can decide how they want to setup their git workflow, I personally prefer squash commits in order to have a linear history. For bigger PRs where you wanna preserve information about the process itself, a rebase commit makes sense, but I try to avoid merge commits as much as possible.

just my 2c on the topics.

**Comment by PLeVasseur** [comment]
Appreciate the feedback @netomi

For the work we're doing, @gregmedd and I encourage developers to have a meaningful commit history prior to merge. Sometimes this is a single commit, sometimes multiple.

Could you expand a little more on the what and why of this:
> For bigger PRs where you wanna preserve information about the process itself, a rebase commit makes sense, but I try to avoid merge commits as much as possible.

Does this keep all the commits in the commit history? Does this bring all the commits in without needing an "extra" merge commit?

**Comment by netomi** [comment]
so there are 3 options to merge a PR on GitHub:

- merge commit
- squash merge
- rebase merge

merge and rebase merges preserve history, with the latter ensuring a linear history to avoid complex merge graphs that become impossible to read / understand for a moderately complex project imho.

squash merge squashes all commits in a PR to a single commit on the target branch while still allows to preserve individual commit information if you want to. For small changesets I prefer squash commits, for larger ones rebase merges.

If you are also getting used to rebases, you can avoid all these "Merge ... into " your PR branch to keep the branch up to date or prior to merging the PR, that avoids a lot of clutter in the commit history imho.

**Pull request merged**
