### PR TITLE
Impacting existing release flow

### PR DESCRIPTION
**Pull request by shaishap**
will be reintroduced once release works

### CODE REVIEW

**Comment by netomi** [comment]
btw. we have just added support for repository rulesets that are very similar to branch protection rules and offer the same functionality. With them it would be possible to enable / disable them on demand without deleting them.

**Comment by stevenhartley** [comment]
@netomi can you please elaborate on what you mean in your above comment? What should we be doing differently?

**Comment by shaishap** [comment]
applied force push permission instaead

**Comment by netomi** [comment]
I was pointing out that the self-service now also supports defining repository rulesets which are improved branch protection rules. They can also be disabled to temporarily support pushing to a branch rather than deleting the rule.

The jetty project uses them already: https://github.com/jetty/.eclipsefdn/blob/main/otterdog/jetty.jsonnet#L154

However in your specific case we should investigate why the release workflow fails. Not sure how just pushing to the main branch will solve that.

**Pull request closed without merging**
