### PR TITLE
Allow 1st class developers to push directly

### PR DESCRIPTION
**Pull request by shaishap**
This is done to allow automation. to run for updating pom.xml on version changes.

### CODE REVIEW

**Comment by netomi** [comment]
We normally do not want to allow force pushes. Also this will not work in your case, as you will not be able to override the required status check with enabling force pushes.

However, the problem that you describe (update the pom in a workflow for the next development cycle) is handled by many projects with a different approach.

Take a look at the eclipse xpanse project where they have a job to do that using a bot:

https://github.com/eclipse-xpanse/xpanse/blob/main/.github/workflows/release.yml#L140-L163

we can also setup a bot token for your organization to do the same. This is a clean solution and is compatible with your existing branch protection rule.

**Comment by shaishap** [comment]
Actually, force push would overcome the check, since there is no PR, thus no checks.
Can you please explain why do you think it'll not work?

We will use a dedicated AccessToken for this step, and not the github_token. I have read many articles on the topic, they all work arround the same issues.
This is required since we want to simplify the handling of the maven -SNAPSHOT versioning by the use of
**mvn release:prepare** target.

**Comment by netomi** [comment]
Sure, I understand with enabling force pushes you make this possible, however with enabling force pushing you render the whole branch protection rule useless so we could just remove it altogether.

Have you taken a look at the workflow that I posted? They also use a token in the workflow (that we provide from the owner of the org) that is able to bypass the branch protection rule.

**Comment by shaishap** [comment]
Not really. we allow it for a single user, and we use that user's github_token only for this part.
I can also block the ability to trigger the release workflow for certain users, thus preventing users from running the workflow. it's actually fairly solid.

**Comment by netomi** [comment]
the change that you requested enables force pushes for everyone.
Again, what you plan to do makes sense, but rather using a token from a specific user, we inject a token from a bot user that is also the owner of the repo, so he can bypass the branch protection rule.

If you follow the workflow that I posted, the commit history will also point out the email of the bot user to indicate that this commit is coming from a workflow.

If you do this, there is no need to adapt the branch protection rule, and the workflow follows the best practices that we use in all projects.

**Comment by shaishap** [comment]
Bot token is ok, as long as we can use it (token) to allow the release:prepare to push to main

**Comment by shaishap** [comment]
Please note the bot token will also need tag release and delete tag permissions.

**Comment by shaishap** [comment]
covered by the addition of the BOT TOKEN. So this PR is no longer needed.

**Pull request closed without merging**
